export const products = [
  {
    coverImage: './assets/img/original.jpg',
    name: 'Phone XL',
    price: 799,
    description: 'A large phone with one of the best screens',
    heading1: 'サンプルテキスト1',
    heading2: 'サンプルテキスト2',
    heading3: 'サンプルテキスト3',
    headingtext1: 'テキスト文章1 テキスト文章1 テキスト文章1 テキスト文章1 テキスト文章1',
    headingtext2: 'テキスト文章2 テキスト文章2 テキスト文章2 テキスト文章2 テキスト文章2',
    headingtext3: 'テキスト文章3 テキスト文章3 テキスト文章3 テキスト文章3 テキスト文章3',
  },
  {
    coverImage: './assets/img/original.jpg',
    name: 'Phone Mini',
    price: 699,
    description: 'A great phone with one of the best cameras',
    heading1: 'サンプルテキスト1',
    heading2: 'サンプルテキスト2',
    heading3: 'サンプルテキスト3',
    headingtext1: 'テキスト文章1 テキスト文章1 テキスト文章1 テキスト文章1 テキスト文章1',
    headingtext2: 'テキスト文章2 テキスト文章2 テキスト文章2 テキスト文章2 テキスト文章2',
    headingtext3: 'テキスト文章3 テキスト文章3 テキスト文章3 テキスト文章3 テキスト文章3',
  },
  {
    coverImage: './assets/img/original.jpg',
    name: 'Phone Standard',
    price: 299,
    description: '',
    heading1: 'サンプルテキスト1',
    heading2: 'サンプルテキスト2',
    heading3: 'サンプルテキスト3',
    headingtext1: 'テキスト文章1 テキスト文章1 テキスト文章1 テキスト文章1 テキスト文章1',
    headingtext2: 'テキスト文章2 テキスト文章2 テキスト文章2 テキスト文章2 テキスト文章2',
    headingtext3: 'テキスト文章3 テキスト文章3 テキスト文章3 テキスト文章3 テキスト文章3',
  },
  {
    coverImage: './assets/img/original.jpg',
    name: 'Phone Special',
    price: 999,
    description: '',
    heading1: 'サンプルテキスト1',
    heading2: 'サンプルテキスト2',
    heading3: 'サンプルテキスト3',
    headingtext1: 'テキスト文章1 テキスト文章1 テキスト文章1 テキスト文章1 テキスト文章1',
    headingtext2: 'テキスト文章2 テキスト文章2 テキスト文章2 テキスト文章2 テキスト文章2',
    headingtext3: 'テキスト文章3 テキスト文章3 テキスト文章3 テキスト文章3 テキスト文章3',
  },

];